
name: required_environment
channels: 
    - conda-forge
    - underworldcode
dependencies:
    - compilers 
    - sympy
    - stripy
    - litho1pt0
    - cartopy
    - obspy
    - pandas
    - pip
    # - libiconv
    # - swig>=4.0.0
    # - scons
    - pip:
      - jupyter-book 
      - xvfbwrapper
      # - lavavu  # probably not critical for the static book
      # - underworldcode # unlikely to build - need a script for this

