
name: required_environment
channels: 
    - conda-forge
    - underworldcode
dependencies:
#     - compilers 
    - cartopy==0.17.*
    - numpy==1.18.1
    - scipy==1.4.1
#    - obspy
#    - pandas
#    - sympy
    - stripy
    - litho1pt0
    # - libiconv
    # - swig>=4.0.0
    # - scons
    - pip:
      - jupyter-book 
      # - xvfbwrapper
      # - lavavu  # probably not critical for the static book
      # - underworldcode # unlikely to build - need a script for this

